apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-new
  name: nginx-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-new
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-new
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
status: {}
